<?php
$a = 10;
$b= 20;
$S = ($a * $b);
$P = (2 * $a) + (2 * $b);
echo "<p>Rectangle a=$a, b=$b, S=$S P=$P </p>";
$a = 15;
$b= 30;
$S = ($a * $b);
$P = (2 * $a) + (2 * $b);
echo "<p>Rectangle a=$a, b=$b, S=$S P=$P </p>";
$a = 1;
$b= 2;
$S = ($a * $b);
$P = (2 * $a) + (2 * $b);
echo "<p>Rectangle a=$a, b=$b, S=$S P=$P </p>";
$a = 15;
$S = $a*$a;
$P = 4 * $a;
echo "<p>Squere a=$a, S=$S P = $P </p>";
$a = 25;
$S = $a*$a;
$P = 4 * $a;
echo "<p>Squere a=$a, S=$S P = $P </p>";
$a = 5;
$S = $a*$a;
$P = 4 * $a;
echo "<p>Squere a=$a, S=$S P = $P </p>";
$a = 10;
$ha = 15;
$S = $a * $ha;
echo "<p>Triangle a=$a Ha = $ha, S=$S  </p>";
$a = 19;
$ha = 25;
$S = $a * $ha;
echo "<p>Triangle a=$a Ha = $ha, S=$S  </p>";
$a = 102;
$ha = 153;
$S = $a * $ha;
echo "<p>Triangle a=$a Ha = $ha, S=$S  </p>";
$r = 15;
$S = $r * pi();
$P = 2 * pi() * $r;
echo "<p>Circle r=$r,P=$P S=$S  </p>";
$r = 1;
$S = $r * pi();
$P = 2 * pi() * $r;
echo "<p>Circle r=$r,P=$P S=$S  </p>";
$r = 5;
$S = $r * pi();
$P = 2 * pi() * $r;
echo "<p>Circle r=$r,P=$P S=$S  </p>";
?>
